import {test} from 'node:test';
import assert from 'node:assert/strict';
import {onRequestPost} from '../functions/api/contact.js';
const valid={submission_id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',name:'Test Person',contact:'test@example.test',message:'Local test only',date:'October',website:'',elapsed:5000};
function context(body=valid,env={},origin='https://example.test'){return {request:new Request('https://example.test/api/contact',{method:'POST',headers:{'Content-Type':'application/json',origin},body:JSON.stringify(body)}),env};}
const env={RESEND_API_KEY:'test-only',ZACHARY_EMAIL:'owner@example.test',FROM_EMAIL:'studio@example.test',PUBLIC_SUPABASE_URL:'https://project.example.test',PUBLIC_SUPABASE_ANON_KEY:'public-test'};
test('rejects another origin without sending mail or saving',async t=>{let calls=0;t.mock.method(globalThis,'fetch',async()=>{calls++;throw new Error('Unexpected network');});assert.equal((await onRequestPost(context(valid,env,'https://other.test'))).status,403);assert.equal(calls,0);});
test('rejects missing required data and unavailable database settings',async()=>{assert.equal((await onRequestPost(context({...valid,message:''}))).status,400);assert.equal((await onRequestPost(context())).status,503);});
test('honeypot and short elapsed time do not save or send mail',async t=>{let calls=0;t.mock.method(globalThis,'fetch',async()=>{calls++;return Response.json({});});await onRequestPost(context({...valid,website:'bot'},env));await onRequestPost(context({...valid,elapsed:1},env));assert.equal(calls,0);});
test('saves draft first, then formats owner mail and acknowledgment with escaped content',async t=>{const calls=[];t.mock.method(globalThis,'fetch',async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});return Response.json(calls.length===1?{ok:true,created:true}:{id:'mock'});});const response=await onRequestPost(context({...valid,name:'<Test>',message:'<script>bad</script>'},env));assert.equal(response.status,200);assert.equal(calls.length,3);assert.equal(calls[0].body.action,'enquire');assert.match(calls[1].body.html,/&lt;script&gt;/);assert.doesNotMatch(calls[1].body.html,/<script>/);assert.equal(calls[1].body.reply_to,'test@example.test');});
test('phone enquiry sends only owner notification',async t=>{let calls=0;t.mock.method(globalThis,'fetch',async()=>{calls++;return Response.json(calls===1?{ok:true,created:true}:{});});assert.equal((await onRequestPost(context({...valid,contact:'229-555-0100'},env))).status,200);assert.equal(calls,2);});
test('an email outage does not discard a saved draft',async t=>{t.mock.method(globalThis,'fetch',async url=>String(url).includes('delivery')?Response.json({ok:true,created:true}):new Response('unavailable',{status:503}));const r=await onRequestPost(context(valid,env));assert.equal(r.status,200);assert.equal((await r.json()).saved,true);});
test('a retry does not resend notifications',async t=>{let calls=0;t.mock.method(globalThis,'fetch',async()=>{calls++;return Response.json({ok:true,created:false});});assert.equal((await onRequestPost(context(valid,env))).status,200);assert.equal(calls,1);});
test('database failure never reports success or sends a misleading acknowledgement',async t=>{let calls=0;t.mock.method(globalThis,'fetch',async()=>{calls++;return new Response('',{status:503});});assert.equal((await onRequestPost(context(valid,env))).status,503);assert.equal(calls,1);});
